### ISSUE TITLE
Firefox does not wrap and truncate long abort messages.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#527]
See: https://nuv.la/run/31faf79c-e8e6-4922-93ea-d9e0460482b8

Same deployment seen on Safari (left) and Firefox (right):

![screen shot 2016-01-18 at 10 41 12](https://cloud.githubusercontent.com/assets/807084/12389338/4e79c1c6-bdd8-11e5-9414-e9f2d8b52a7b.png)

After playing with the CSS rules with @schaubl, we found that the following rule in [`alert.css:24`](https://github.com/slipstream/SlipStreamUI/blob/7292ee6a537c856dcdc88cebfaa9f18170a8401f/clj/resources/static_content/css/alerts.css#L24) must be changed from

```css
.alert-msg {
    word-break: break-word;
}
```

to

```css
.alert-msg {
    word-wrap: break-word;
}
```

i.e. `word-break` into `word-wrap`.

Reference: http://stackoverflow.com/questions/1795109/what-is-the-difference-between-word-break-break-all-versus-word-wrap-break
